version: '3.8'
services:
  redstaroxus:
    image: postgres:15-alpine
    restart: always
    container_name: ${CONTAINER_NAME}
    environment:
      TZ: "Asia/Tashkent"
      PGTZ: "Asia/Tashkent"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    command: postgres -c 'max_connections=1000'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - redd:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  redd: