version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      TZ: "Asia/Tashkent"
      PGTZ: "Asia/Tashkent"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    command: postgres -c 'max_connections=1000'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env

  nrg-redis:
    image: redis:latest
    command: redis-server --databases 32
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379


volumes:
  postgres-volume:
  redis:
  redis-config: