# Generated by Django 5.0.6 on 2024-07-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.CharField(max_length=50, unique=True, verbose_name='Bike Number')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('bike_type', models.CharField(choices=[('urban', 'Urban'), ('mountain', 'Mountain'), ('road', 'Road'), ('hybrid', 'Hybrid'), ('cruiser', 'Cruiser'), ('bmx', 'BMX')], max_length=10, verbose_name='Bike Type')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bicycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bicycle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bicycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
