# Generated by Django 5.0.6 on 2024-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bicycle_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='bike_type',
            field=models.CharField(choices=[('urban', 'Urban'), ('mountain', 'Mountain'), ('road', 'Road')], max_length=10, verbose_name='Bike Type'),
        ),
    ]
