# Generated by Django 5.0.6 on 2024-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bicycle_bike_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
